# Generated by Django 3.1.4 on 2021-01-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
                ('opis', models.TextField(max_length=256)),
                ('jest_dostepny', models.BooleanField(default=True)),
            ],
        ),
    ]
