# Generated by Django 3.1.5 on 2021-01-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cena',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ocena_uzytkownika',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rozmiar',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='jest_dostepny',
            field=models.BooleanField(default=False),
        ),
    ]
