# Generated by Django 3.1.5 on 2021-01-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210126_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ocena_uzytkownika',
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(3, 'Spodniczka'), (5, 'Spodnie'), (4, 'Zakiet'), (1, 'Sukienka'), (2, 'Suknia'), (0, 'Nieznany')], default=0),
        ),
    ]
