# Generated by Django 3.1.5 on 2021-01-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210126_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('addres', models.TextField(blank=True, null=True)),
                ('nr_telefonu', models.CharField(blank=True, max_length=12, null=True)),
                ('adres_mailowy', models.EmailField(max_length=45)),
                ('czas_dodania', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(2, 'Suknia'), (0, 'Nieznany'), (1, 'Sukienka'), (5, 'Spodnie'), (3, 'Spodniczka'), (4, 'Zakiet')], default=0),
        ),
        migrations.AlterField(
            model_name='opinia',
            name='produkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinie', to='api.product'),
        ),
    ]
