# Generated by Django 3.1.5 on 2021-01-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210126_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzytkownik',
            old_name='addres',
            new_name='adres',
        ),
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(2, 'Suknia'), (5, 'Spodnie'), (4, 'Zakiet'), (1, 'Sukienka'), (3, 'Spodniczka'), (0, 'Nieznany')], default=0),
        ),
    ]
